### ISSUE TITLE
Random movement 

### ISSUE THREAD

**Issue by kraj011** [jordanbancino/SwerveIO#14] opened 2019-12-17 15:11 UTC
**Describe the bug**

So I just finished setting up our MK2 modules and I set up all the code to use SwerveIO. I added our encoder offsets and length and width of the chassis. Unfortunately, for example, when I do drive(0, 0, 0, 0), it starts randomly rotating perpetually. I have no idea why. 

**To Reproduce**

1. Setup code
2. Run drive(0, 0, 0, 0);

**Expected behavior**

It should snap the wheels to the zero / forward position. 

**Additional context**

I setup all the CAN ID's properly and the rest of the mapping should be right as well.

**Comment by jordanbancino** [comment] 2019-12-17 15:14
Oh dear God. Well, I can tell you right now that that's our PID loop screwing us over. This is gonna be a tough one. What PID values are you using? Additionally, what version of SwerveIO are you using? I think the latest commits could have broke something, I can try reverting that back for you.

**Comment by jordanbancino** [comment] 2019-12-17 15:16
Actually, yeah, I think I know what it could be. I'm going to fix it right now!

**Comment by kraj011** [comment] 2019-12-17 15:17
Sounds good!! Thanks! I'll test it out in like an hour and let you know!

**Comment by jordanbancino** [comment] 2019-12-17 15:19
I may be a while, the code is a little different than I remember. I'd recommend using version 1.0 though, I think that should work. See what your results are for that. If you're already using version 1.0, then try using the master branch.

**Comment by kraj011** [comment] 2019-12-17 16:03
I saw you updated something for the current version. Should I try that out or stick to version 1?

**Comment by kraj011** [comment] 2019-12-17 16:32
Just tried both and no luck D:

**Comment by kraj011** [comment] 2019-12-17 16:37
Let me know if you need me to send a video :D

**Comment by jordanbancino** [comment] 2019-12-17 18:40
Well darn, that's sad. Yes, a video would be much appreciated, at least I could try to figure out what it's doing.

**Comment by kraj011** [comment] 2019-12-17 19:40
Do you have an email, discord, etc. I could send it to? Thanks

**Comment by jordanbancino** [comment] 2019-12-17 21:01
I believe you can upload files right to this thread, but if you'd like, my email should be available on my GitHub profile.
---
I think what the issue is is something not being modded properly in the drive function. What I mean is, I think I need to apply the modulus operator to something... to prevent it from constantly changing the reference. I'm not entirely sure though, I'll have to work on it later.

This whole thing is just so weird to me because it works flawlessly for our robot...

**Comment by kraj011** [comment] 2019-12-17 22:05
Yea I mean it's definitely possible that I'm doing something wrong on my end. I pretty much just clones your team's example code using SwerveIO to test. 

[IMG_5504.MOV.zip](https://github.com/Team6090/SwerveIO/files/3975678/IMG_5504.MOV.zip)

Here is a video of it running at drive(0,0,0);

**Comment by jordanbancino** [comment] 2019-12-17 22:40
Hmmmm. Interesting. That's so odd. I guess, can I see your exact code?

**Comment by jordanbancino** [comment] 2019-12-17 22:42
Oh, did you verify that all the encoders are working properly?

**Comment by kraj011** [comment] 2019-12-18 00:08
I believe i did. The only testing i did with the encoders was pulling their zero position so i assume they’re working properly. I’ll test them again tomorrow morning but they should be working!

**Comment by kraj011** [comment] 2019-12-18 23:41
Quick update :) got to test again today turns out our encoders were plugged into pwm and not analog input! Fixed that up but still getting some weird movement

**Comment by jordanbancino** [comment] 2019-12-19 00:56
Oh awesome! Ah, I see. Is the movement related to #13 perhaps?

**Comment by kraj011** [comment] 2019-12-19 00:58
I don't believe so. It's weird. I'll do some more testing tomorrow but it basically seems like random movement based on my input. I'll try tomorrow to pass in some constant values into my drive command and see what happens. I'll update this thread when I get the chance to test! Is there anything else you suggest I try?

**Comment by jordanbancino** [comment] 2019-12-19 01:06
Interesting. Alright, that sounds good. As far as suggestions go, I'm not quite sure. We obviously know that SwerveIO needs quite a bit of work. So I'm hoping that as we develop it more some of these things will be worked out. But yes, keep me updated and videos are always welcome. I'll try to help you as best I can.

**Comment by kraj011** [comment] 2019-12-29 17:43
Possible problem with spark maxes? https://www.chiefdelphi.com/t/team-2910-code-release-2019/359697/26

**Comment by jordanbancino** [comment] 2019-12-29 17:51
For my sake, I sure hope so! But of course, for your sake, that sounds difficult to troubleshoot. I have no idea if that's what it is or not, our spark maxes are working flawlessly, but then, we haven't updated to the latest firmware. So I have no idea. This does seem like the most plausible explanation so far though. Is the movement described on that page what you're experiencing?

**Comment by kraj011** [comment] 2019-12-29 17:57
Yea so the videos / descriptions of the issues do match up with what I am experiencing. We updated the spark maxes to the latest firmware which I thought could have been an issue, but it seems that it might not be an issue according to the thread? Something that does concern me is that they say that the fix (atleast temporarily) was to switch everything to CAN. We tried out Swervedrivespecialties' example code for the MK2 modules and it would make sense to try that (would need to break and mess around with some of their library's code to make it work but hey),  however for SwerveIO we had only used CAN and were getting the same issue. I'm gonna go ahead and troubleshoot some more and see what I can do! I'll keep this thread updated with any progress or further issues!

**Comment by jordanbancino** [comment] 2019-12-29 17:59
Oh interesting. I see. Wow, yikes. Yeah, I’ve never even considered doing it any other way than CAN. Huh, yeah, that’s frightening and very odd. Okay, yes please, keep us updated! Thanks!

**Comment by kraj011** [comment] 2019-12-30 02:03
Welp this is probably good news but after hours of troubleshooting and realizing that only one of my encoders were working, turns out the other 3 are wired incorrectly! I'm going to go ahead and rewire them and send an update in here =!

**Comment by jordanbancino** [comment] 2019-12-30 02:37
Ohhhh wow, nice. Haha, well I'm glad you're making progress! Thanks for keeping me updated!

**Comment by jordanbancino** [comment] 2020-01-05 13:13
We updated our Spark Maxes to the latest firmware (1.5.1) yesterday and everything is still working fine. We also updated SwerveIO to use the new command framework. Make sure you check the README for the latest version. And I finally set up a Maven repository, so it'd be best to pull it from there.

**Comment by kraj011** [comment] 2020-01-05 19:49
perfect will do! We have some issues with our wiring that we have to fix before we continue to test. I remember i tried SwerveIO once i had everything working and the issue i experienced was the wheels seemed like they were going to a target encoder value and they kept oscillating and seemed like they never reached their target angle. I would have to do more testing once we fix up the wiring to verify but that seemed like the only issue. Maybe i have to tune the PID values?

**Comment by jordanbancino** [comment] 2020-01-06 11:50
Alright, cool! Yeah, you may have to mess with the PID values. You can do so in the `ModuleModifier` that you can pass into the `SwerveDrive` constructor. I sorta thought that tuning it once would work for pretty much everything since it's the exact same kit, but perhaps not.

**Comment by jordanbancino** [comment] 2020-02-02 18:13
Any news for us? @kraj011

**Comment by kraj011** [comment] 2020-02-03 14:03
Hey! We've been using SDS's library while we were getting everything setup. Now that everything is working I'll setup a new project using SwerveIO and let you know!

**Comment by jordanbancino** [comment] 2020-02-03 14:33
Ah, alright cool. I'll have to update the instructions, quite a few things have changed.

**Comment by jordanbancino** [comment] 2020-10-20 16:16
Hopefully you're happy with whatever you're using now. I'm closing this because we aren't having this issue with out robot.

**Closed by jordanbancino** 2020-10-20 16:16 UTC
Labels: bug, help wanted
